services:
  postgres:
    image: postgres:17
    container_name: postgress
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agent_platform
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/maildir
    volumes:
      - ./data/maildata:/maildir

  elasticmq:
    image: softwaremill/elasticmq-native:latest
    container_name: event-queue
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf

  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    container_name: pubsub-emulator
    command: >
      bash -c "
        gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 &
        sleep 5 &&
        export PUBSUB_EMULATOR_HOST=localhost:8085 &&
        gcloud pubsub topics create gmail-notifications &&
        gcloud pubsub subscriptions create gmail-sub --topic=gmail-notifications &&
        tail -f /dev/null
      "
    ports:
      - "8085:8085"
    environment:
      - PUBSUB_EMULATOR_HOST=0.0.0.0:8085

volumes:
  postgres_data: