services:
  postgres:
    image: postgres:17
    container_name: postgress
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agent_platform
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  elasticmq:
    image: softwaremill/elasticmq-native:latest
    container_name: agent_mq
    ports:
      - "9324:9324"
      - "9325:9325"

  app:
    build:
      context: ./app
    container_name: rs-app
    command: sh -c "cargo run --bin main & cargo run --bin worker"
    depends_on:
      - postgres
      - elasticmq
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/agent_platform
      - AWS_ENDPOINT_URL=http://elasticmq:9324
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=ap-northeast-1
      - SQS_QUEUE_URL=http://elasticmq:9324/000000000000/tasks
      - PYTHON_AGENT_URL=http://python_agents:8000
    restart: on-failure

  agents:
    build:
      context: ./agents
    container_name: agents
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: on-failure

volumes:
  postgres_data: