edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true
format_strings = true
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20
